public let ID_SEPARATOR = "&"
public let CLOUDCARDS_WEBSITE = "cloudcards.h1n.ru"

public let NAME = "имя"
public let SURNAME = "фамилия"
public let PATRONYMIC = "отчество"
public let COMPANY = "компания"
public let JOB_TITLE = "должность"
public let MOBILE = "мобильный номер"
public let MOBILE_OTHER = "мобильный номер (другой)"
public let EMAIL = "электронная почта"
public let EMAIL_OTHER = "электронная почта (другая)"
public let ADDRESS = "адрес"
public let ADDRESS_OTHER = "адрес (другой)"
public let WEBSITE = "сайт"
public let VK = "vk"
public let TELEGRAM = "telegram"
public let FACEBOOK = "facebook"
public let INSTAGRAM = "instagram"
public let TWITTER = "twitter"

public let COMPANY_NAME = "наименование"
public let COMPANY_RESPONSIBLE = "ответственный"
public let COMPANY_RESPONSIBLE_JOB_TITLE = "должность ответственного"
public let COMPANY_ADDRESS = "адрес"
public let COMPANY_PHONE = "телефон"
